modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "gensokyoizakaya"
version = "${version}"
displayName = "幻雀妖"
authors = "烟花,Aurora040123,仿生狐狸,CreativeEVW,Direct9021"
description = '''
一个模拟经营与美食模组
'''
logoFile = "assets/gensokyoizakaya/icon.png"

[[dependencies.gensokyoizakaya]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gensokyoizakaya]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gensokyoizakaya]]
modId = "farmersdelight"
type = "required"
versionRange = "[1.2.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gensokyoizakaya]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "gensokyoizakaya.mixins.json"
