modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "touhoupixelcanteen"
version = "${version}"
displayName = "幻雀妖"
authors = "烟花,Aurora040123,CreativeEVW,Direct9021"
description = '''
一个模拟经营与美食模组
'''
#logoFile = ""

[[dependencies.touhoupixelcanteen]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.touhoupixelcanteen]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.touhoupixelcanteen]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "touhoupixelcanteen.mixins.json"
